### ISSUE TITLE
Does it work?

### ISSUE THREAD

**Issue by zquintana** [simonluijk/django-invoice#1]
Does this project work? I'd like to use it if it does. If it does, anyway you could submit to pypi.python.org so it will be easy to install/manage?

**Comment by simonluijk** [comment]
Yes it works. It is also on pipi as django-invoice. Sorry I have not had the time to create the documentation. I hope to add documentation but I don't expect it to be soon.

**Comment by skizzy** [comment]
When are you planning to add the documentation?

**Comment by skizzy** [comment]
I want to use it but due to docs I can't! :(

**Comment by simonluijk** [comment]
As I am rather busy I will not be able to get full documentation anytime
soon. But I will commit to getting a readme style documentation in the next
few days.

I would be happy to accept PRs from someone who has used django-invoice :)

**Comment by simonluijk** [comment]
Documentation has been added in the form of a basic read me.
